---

- name: install required packages
  ansible.builtin.apt:
    name:
      - dkms
      - libelf-dev
      - linux-headers-{{ ansible_kernel | default(kernel_release.stdout) }}
      - build-essential
    state: present
